
[workspace]
resolver = "3"
members = ["crates/*"]
[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Albert O'Shea <albertoshea2@gmail.com>"]
description = "Query Rust docs and crate API from the command line"
license = "MIT"
repository = "https://github.com/Alb-O/ripdoc"
readme = "README.md"
keywords = ["docs", "documentation", "outline", "cli"]

[workspace.lints.rust]
missing_docs = "warn"

[workspace.dependencies]
once_cell = { version = "1.21", default-features = false }
ripdoc-cargo = { path = "crates/ripdoc-cargo", version = "*"}
ripdoc-cli = { path = "crates/ripdoc-cli", version = "*"}
ripdoc-core = { path = "crates/ripdoc-core", version = "*"}
ripdoc-render = { path = "crates/ripdoc-render", version = "*"}
rust-format = { version = "0.3", default-features = false }
rustdoc-types = { version = "0.57", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[patch.crates-io]
rustdoc-json = { git = "https://github.com/Alb-O/cargo-public-api" }
cargo-manifest = { git = "https://github.com/Alb-O/cargo-manifest" }
