[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Albert O'Shea <albertoshea2@gmail.com>"]
description = "Query and outline Rust documentation from the command line"
license = "MIT"
repository = "https://github.com/Alb-O/ripdoc"
readme = "README.md"
keywords = ["docs", "documentation", "outline", "cli"]

[workspace.lints.rust]
missing_docs = "warn"

[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["vendor/cargo-public-api", "vendor/cargo-manifest"]

[workspace.dependencies]
libripdoc = { version = "0.1.0", path = "crates/libripdoc" }

[patch.crates-io]
rustdoc-json = { path = "vendor/cargo-public-api/rustdoc-json" }
cargo-manifest = { path = "vendor/cargo-manifest" }